version: 2

jobs:
  check-flake8:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - run:
          name: Installing flake8
          command: 'sudo pip install flake8'
      - checkout
      - run: 
          name: Checking for flake8 errors
          command: 'flake8 '
          
   build-status:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: Build
          command: 'python src/__init__.py'
          
workflows:
  version: 2
  build:
    jobs:
      -check-flake8
      -build-status
  
