version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - checkout
      - run: echo "A first hello"
