version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing flake8
          command: 'sudo pip install flake8 -y'
      - checkout
      - run: 
        name: Checking for flake8 errors
        command: 'flake8'
