version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - run:
          name: Installing flake8
          command: 'pip install flake8'
      - checkout
      - run: 
          name: Checking for flake8 errors
          command: 'flake8 '
